### ISSUE TITLE
Consider using provide/inject

### ISSUE THREAD

**Issue by blocka** [jaredramirez/vuedux#2]
Now that vue has support for provide/inject, would you consider using that instead of your custom provider component?

**Comment by jaredramirez** [comment]
Yeah, definitely!

It was my intention to use provide/inject after it was merged in the core, but I totally forgot. Will do within the next day or two.

**Comment by jaredramirez** [comment]
Sorry that this is still pending! Been really busy swamped lately, but hoping to get this change in sometime this week.

**Comment by jaredramirez** [comment]
Finished and published in `v0.0.10` along with a few other updates.
https://github.com/jaredramirez/vuedux/releases/tag/v0.0.10
@blocka
